repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier (write)
        entry: npx prettier --write
        language: system
        files: \.(js|jsx|ts|tsx|json|css|scss|md|mdx|html|yml|yaml)$
        exclude: ^(node_modules/|dist/|server/\.env|.*\.env(\..*)?$|.*\.svg$)
